[project]
name = 'gpt-oss-cli'
version = '0.1.0'
description = 'Efficient CLI for OpenAI-compatible LLMs with GPT-OSS-20B integration'
requires-python = '>=3.10'
dependencies = [
    'httpx>=0.28.1',
    'typer>=0.16.0',
    'rich>=13.7.1',
    'pydantic>=2.7.0',
    'python-dotenv>=1.0.1',
]
